{{- if .Values.vault.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.vault.secretStoreName }}
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    vault:
      server: {{ .Values.vault.address | quote }}
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: {{ .Values.vault.auth.role | quote }}
          serviceAccountRef:
            name: {{ .Values.vault.auth.serviceAccount | quote }}
          audiences:
            - "vault"
{{- end }}
